POST http://localhost:8000/api/route
Accept: */*
Cache-Control: no-cache

{"kbs": 252,  "name": "Foreign infrastructure",  "stations_name": "Berlin Chabrunnen - Leipzig Hbf",  "length": 161600,  "max_permitted_speed": 320 }

###